name: DataSync
version: ${project.version}
main: org.nocraft.loperd.datasync.spigot.DataSyncBootstrapBukkit
api-version: 1.13
authors: [loperd]
depend: [DeltaRedis]
description: Plugin for synchronize all playerdata like armor, inventory, enderchest, etc.. between servers around BungeeCord/Waterfall proxy.